### ISSUE TITLE
[Feature request] Remove systemd dependency

### ISSUE THREAD

**Issue by ifohancroft** [falconindy/auracle#103]
I have idea why auracle even depends on systemd to begin with, but please remove the dependency so that I, and everyone else that have switched to a systemd-free system can continue using it.

**Comment by Narrat** [comment]
It uses [sd-event.h](https://www.freedesktop.org/software/systemd/man/sd-event.html) from libystemd.
And looking at the commit where it got [introduced](https://github.com/falconindy/auracle/commit/f79bd5ca5e61992fca4e98198ad8d0bc7bb45672) there was a reason for it. And as it seems to be a crucial component in how auracle works I doubt it will be replaced that easily. Especially since this is a rather dormant project.

**Comment by falconindy** [comment]
Correct, the sd-event dependency isn't going away. You can install the systemd libraries without using systemd.
