### ISSUE TITLE
Add AUR comments

### ISSUE THREAD

**Issue by jnumbers** [falconindy/auracle#15]
When running into package build errors, the first place I tend to look are the AUR comments. Usually a solution will be posted from either the author or a user. Having the ability to search comments with auracle would make solving these errors much faster and easier.

**Comment by AladW** [comment]
On Tue, Feb 27, 2018 at 05:36:35AM +0000, jnumbers wrote:
> When running into package build errors, the first place I tend to look are the AUR comments. Usually a solution will be posted from either the author or a user. Having the ability to search comments with auracle would make solving these errors much faster and easier. 
> 
There's already aur-comment-fetcher, not sure why a web scraper should
be implemented in auracle. cower didn't have it either

$ aur comment-fetch auracle-git

Last 5 comments for package "auracle-git":
 full info at https://aur.archlinux.org/packages/auracle-git

2018-02-21 10:31: Comment by heftig
  Can't you use https://github.com/nlohmann/json/releases/download/v3.
  1.1/include.zip directly? The nlohmann-json package has no point.
2018-02-08 01:03: Comment by bhoppi
  Maybe nlohmann-json is just a makedepends? After compiling auracle,
  it won't be needed any more.
2018-01-31 14:42: Comment by Eschwartz
  Since nlohmann-json takes so long to build, I have a custom repo for
  it here: https://wiki.archlinux.org/index.php/Unofficial_user_reposi
  tories#eschwartz
2017-12-02 20:14: Comment by falconindy
  No, it's optional and adds nothing when present.
2017-12-02 19:51: Comment by ilpianista
  > Program ragel found: NO   Does this require ragel as dependency?
.

**Comment by falconindy** [comment]
Agreed, this has no place in auracle.
